# --------------------------------------------------------------------------------
# Costum defined Apple cross-compile images.
# They should not be public because of Apple licencing restrictions.
# https://github.com/cross-rs/cross/
# See https://github.com/cross-rs/cross-toolchains?tab=readme-ov-file#apple-targets
# SDKs can be downloaded here: https://github.com/joseluisq/macosx-sdks
# Images are uploaded to the Github Registry. Docker login required.
# @Sev May 2025
# --------------------------------------------------------------------------------


[target.aarch64-apple-darwin]
image = "ghcr.io/pubky/aarch64-apple-darwin-cross:latest"

[target.x86_64-apple-darwin]
image = "ghcr.io/pubky/x86_64-apple-darwin-cross:latest"