[package]
name = "pubky-wasm"
version = "0.5.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
console_log = { version = "1.0.0", features = ["color"] }
log = "0.4.25"
web-sys = "0.3.77"
js-sys = "0.3.77"
wasm-bindgen-futures = "0.4.50"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
tsify = "0.5.5"
pubky = { path = "../../../pubky-client" }
pkarr = { version = "3.7.1", features = ["full"] }
pubky-common = { path = "../../../pubky-common" }
