name: Build Artifacts

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install cross
        run: cargo install cross --locked
      - name: Add MacOS target
        run: rustup target add x86_64-apple-darwin aarch64-apple-darwin
      - name: Build Artifacts
        run: .scripts/create-release-gzips.sh
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          path: target/github-release/*
          if-no-files-found: error
          compression-level: 0
          overwrite: true


