name: Build Artifacts

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install cross
        run: cargo install cross --locked
      - name: Build Artifacts
        run: .scripts/build-artifacts.sh


