name: Build Artifacts

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install cross # Tool to cross-compile the binaries
        run: cargo install cross --locked
      - name: Build Artifacts
        run: .scripts/build-artifacts.sh
      - name: gzip all the artifacts
        run: (cd target && tar -czf github-release.tar.gz github-release)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pubky-core-artifacts.tar.gz
          path: target/github-release.tar.gz
          if-no-files-found: error
          overwrite: true


